// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/g-villarinho/tab-notes-api/models"
	mock "github.com/stretchr/testify/mock"
)

// AuthServiceMock is an autogenerated mock type for the AuthService type
type AuthServiceMock struct {
	mock.Mock
}

type AuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthServiceMock) EXPECT() *AuthServiceMock_Expecter {
	return &AuthServiceMock_Expecter{mock: &_m.Mock}
}

// AuthenticateFromLink provides a mock function with given fields: ctx, token
func (_m *AuthServiceMock) AuthenticateFromLink(ctx context.Context, token string) (*models.AuthResponse, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateFromLink")
	}

	var r0 *models.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.AuthResponse, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.AuthResponse); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthServiceMock_AuthenticateFromLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateFromLink'
type AuthServiceMock_AuthenticateFromLink_Call struct {
	*mock.Call
}

// AuthenticateFromLink is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *AuthServiceMock_Expecter) AuthenticateFromLink(ctx interface{}, token interface{}) *AuthServiceMock_AuthenticateFromLink_Call {
	return &AuthServiceMock_AuthenticateFromLink_Call{Call: _e.mock.On("AuthenticateFromLink", ctx, token)}
}

func (_c *AuthServiceMock_AuthenticateFromLink_Call) Run(run func(ctx context.Context, token string)) *AuthServiceMock_AuthenticateFromLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthServiceMock_AuthenticateFromLink_Call) Return(_a0 *models.AuthResponse, _a1 error) *AuthServiceMock_AuthenticateFromLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthServiceMock_AuthenticateFromLink_Call) RunAndReturn(run func(context.Context, string) (*models.AuthResponse, error)) *AuthServiceMock_AuthenticateFromLink_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, sessionId
func (_m *AuthServiceMock) Logout(ctx context.Context, sessionId string) error {
	ret := _m.Called(ctx, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthServiceMock_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthServiceMock_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionId string
func (_e *AuthServiceMock_Expecter) Logout(ctx interface{}, sessionId interface{}) *AuthServiceMock_Logout_Call {
	return &AuthServiceMock_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionId)}
}

func (_c *AuthServiceMock_Logout_Call) Run(run func(ctx context.Context, sessionId string)) *AuthServiceMock_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthServiceMock_Logout_Call) Return(_a0 error) *AuthServiceMock_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthServiceMock_Logout_Call) RunAndReturn(run func(context.Context, string) error) *AuthServiceMock_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// SendAuthenticationLink provides a mock function with given fields: ctx, email
func (_m *AuthServiceMock) SendAuthenticationLink(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for SendAuthenticationLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthServiceMock_SendAuthenticationLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAuthenticationLink'
type AuthServiceMock_SendAuthenticationLink_Call struct {
	*mock.Call
}

// SendAuthenticationLink is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AuthServiceMock_Expecter) SendAuthenticationLink(ctx interface{}, email interface{}) *AuthServiceMock_SendAuthenticationLink_Call {
	return &AuthServiceMock_SendAuthenticationLink_Call{Call: _e.mock.On("SendAuthenticationLink", ctx, email)}
}

func (_c *AuthServiceMock_SendAuthenticationLink_Call) Run(run func(ctx context.Context, email string)) *AuthServiceMock_SendAuthenticationLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthServiceMock_SendAuthenticationLink_Call) Return(_a0 error) *AuthServiceMock_SendAuthenticationLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthServiceMock_SendAuthenticationLink_Call) RunAndReturn(run func(context.Context, string) error) *AuthServiceMock_SendAuthenticationLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthServiceMock creates a new instance of AuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceMock {
	mock := &AuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
