// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// EnvironmentHandlerMock is an autogenerated mock type for the EnvironmentHandler type
type EnvironmentHandlerMock struct {
	mock.Mock
}

type EnvironmentHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EnvironmentHandlerMock) EXPECT() *EnvironmentHandlerMock_Expecter {
	return &EnvironmentHandlerMock_Expecter{mock: &_m.Mock}
}

// GetEnvs provides a mock function with given fields: w, r
func (_m *EnvironmentHandlerMock) GetEnvs(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// EnvironmentHandlerMock_GetEnvs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvs'
type EnvironmentHandlerMock_GetEnvs_Call struct {
	*mock.Call
}

// GetEnvs is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *EnvironmentHandlerMock_Expecter) GetEnvs(w interface{}, r interface{}) *EnvironmentHandlerMock_GetEnvs_Call {
	return &EnvironmentHandlerMock_GetEnvs_Call{Call: _e.mock.On("GetEnvs", w, r)}
}

func (_c *EnvironmentHandlerMock_GetEnvs_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *EnvironmentHandlerMock_GetEnvs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *EnvironmentHandlerMock_GetEnvs_Call) Return() *EnvironmentHandlerMock_GetEnvs_Call {
	_c.Call.Return()
	return _c
}

func (_c *EnvironmentHandlerMock_GetEnvs_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *EnvironmentHandlerMock_GetEnvs_Call {
	_c.Run(run)
	return _c
}

// NewEnvironmentHandlerMock creates a new instance of EnvironmentHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnvironmentHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EnvironmentHandlerMock {
	mock := &EnvironmentHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
