// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// FeedHandlerMock is an autogenerated mock type for the FeedHandler type
type FeedHandlerMock struct {
	mock.Mock
}

type FeedHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FeedHandlerMock) EXPECT() *FeedHandlerMock_Expecter {
	return &FeedHandlerMock_Expecter{mock: &_m.Mock}
}

// GetFeed provides a mock function with given fields: w, r
func (_m *FeedHandlerMock) GetFeed(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// FeedHandlerMock_GetFeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeed'
type FeedHandlerMock_GetFeed_Call struct {
	*mock.Call
}

// GetFeed is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *FeedHandlerMock_Expecter) GetFeed(w interface{}, r interface{}) *FeedHandlerMock_GetFeed_Call {
	return &FeedHandlerMock_GetFeed_Call{Call: _e.mock.On("GetFeed", w, r)}
}

func (_c *FeedHandlerMock_GetFeed_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *FeedHandlerMock_GetFeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *FeedHandlerMock_GetFeed_Call) Return() *FeedHandlerMock_GetFeed_Call {
	_c.Call.Return()
	return _c
}

func (_c *FeedHandlerMock_GetFeed_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *FeedHandlerMock_GetFeed_Call {
	_c.Run(run)
	return _c
}

// NewFeedHandlerMock creates a new instance of FeedHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeedHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeedHandlerMock {
	mock := &FeedHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
