// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/g-villarinho/tab-notes-api/models"
	mock "github.com/stretchr/testify/mock"
)

// HealthServiceMock is an autogenerated mock type for the HealthService type
type HealthServiceMock struct {
	mock.Mock
}

type HealthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthServiceMock) EXPECT() *HealthServiceMock_Expecter {
	return &HealthServiceMock_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: ctx
func (_m *HealthServiceMock) Check(ctx context.Context) models.HealthStatus {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 models.HealthStatus
	if rf, ok := ret.Get(0).(func(context.Context) models.HealthStatus); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.HealthStatus)
	}

	return r0
}

// HealthServiceMock_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type HealthServiceMock_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HealthServiceMock_Expecter) Check(ctx interface{}) *HealthServiceMock_Check_Call {
	return &HealthServiceMock_Check_Call{Call: _e.mock.On("Check", ctx)}
}

func (_c *HealthServiceMock_Check_Call) Run(run func(ctx context.Context)) *HealthServiceMock_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HealthServiceMock_Check_Call) Return(_a0 models.HealthStatus) *HealthServiceMock_Check_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthServiceMock_Check_Call) RunAndReturn(run func(context.Context) models.HealthStatus) *HealthServiceMock_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewHealthServiceMock creates a new instance of HealthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthServiceMock {
	mock := &HealthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
