// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenServiceMock is an autogenerated mock type for the TokenService type
type TokenServiceMock struct {
	mock.Mock
}

type TokenServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenServiceMock) EXPECT() *TokenServiceMock_Expecter {
	return &TokenServiceMock_Expecter{mock: &_m.Mock}
}

// GenerateAuthToken provides a mock function with given fields: ctx, userID, sessionID, iat, exp
func (_m *TokenServiceMock) GenerateAuthToken(ctx context.Context, userID string, sessionID string, iat time.Time, exp time.Time) (string, error) {
	ret := _m.Called(ctx, userID, sessionID, iat, exp)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAuthToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) (string, error)); ok {
		return rf(ctx, userID, sessionID, iat, exp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) string); ok {
		r0 = rf(ctx, userID, sessionID, iat, exp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, sessionID, iat, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenServiceMock_GenerateAuthToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAuthToken'
type TokenServiceMock_GenerateAuthToken_Call struct {
	*mock.Call
}

// GenerateAuthToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
//   - iat time.Time
//   - exp time.Time
func (_e *TokenServiceMock_Expecter) GenerateAuthToken(ctx interface{}, userID interface{}, sessionID interface{}, iat interface{}, exp interface{}) *TokenServiceMock_GenerateAuthToken_Call {
	return &TokenServiceMock_GenerateAuthToken_Call{Call: _e.mock.On("GenerateAuthToken", ctx, userID, sessionID, iat, exp)}
}

func (_c *TokenServiceMock_GenerateAuthToken_Call) Run(run func(ctx context.Context, userID string, sessionID string, iat time.Time, exp time.Time)) *TokenServiceMock_GenerateAuthToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *TokenServiceMock_GenerateAuthToken_Call) Return(_a0 string, _a1 error) *TokenServiceMock_GenerateAuthToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenServiceMock_GenerateAuthToken_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) (string, error)) *TokenServiceMock_GenerateAuthToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateMagicLinkToken provides a mock function with given fields: ctx, email, iat, exp
func (_m *TokenServiceMock) GenerateMagicLinkToken(ctx context.Context, email string, iat time.Time, exp time.Time) (string, error) {
	ret := _m.Called(ctx, email, iat, exp)

	if len(ret) == 0 {
		panic("no return value specified for GenerateMagicLinkToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (string, error)); ok {
		return rf(ctx, email, iat, exp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) string); ok {
		r0 = rf(ctx, email, iat, exp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, email, iat, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenServiceMock_GenerateMagicLinkToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateMagicLinkToken'
type TokenServiceMock_GenerateMagicLinkToken_Call struct {
	*mock.Call
}

// GenerateMagicLinkToken is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - iat time.Time
//   - exp time.Time
func (_e *TokenServiceMock_Expecter) GenerateMagicLinkToken(ctx interface{}, email interface{}, iat interface{}, exp interface{}) *TokenServiceMock_GenerateMagicLinkToken_Call {
	return &TokenServiceMock_GenerateMagicLinkToken_Call{Call: _e.mock.On("GenerateMagicLinkToken", ctx, email, iat, exp)}
}

func (_c *TokenServiceMock_GenerateMagicLinkToken_Call) Run(run func(ctx context.Context, email string, iat time.Time, exp time.Time)) *TokenServiceMock_GenerateMagicLinkToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *TokenServiceMock_GenerateMagicLinkToken_Call) Return(_a0 string, _a1 error) *TokenServiceMock_GenerateMagicLinkToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenServiceMock_GenerateMagicLinkToken_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) (string, error)) *TokenServiceMock_GenerateMagicLinkToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenServiceMock creates a new instance of TokenServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenServiceMock {
	mock := &TokenServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
