version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: tabnotes-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tabnotes
      MYSQL_USER: tabnotes_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
